# Generated by Django 6.0.4 on 2026-05-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('ingredient_id', models.AutoField(db_column='Ingredient_id', primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(db_column='Ingredient_name')),
                ('formula_type', models.CharField(blank=True, db_column='Formula_type', null=True)),
            ],
            options={
                'db_table': 'Ingredients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(db_column='Inventory_id', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
                ('expiration_date', models.DateField(blank=True, db_column='Expiration_date', null=True)),
                ('product_name', models.CharField(blank=True, db_column='Product_name', null=True)),
                ('cost', models.DecimalField(blank=True, db_column='Cost', decimal_places=5, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('supplement_id', models.AutoField(db_column='Supplement_ID', primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='Product_name')),
                ('manufacturer', models.CharField(blank=True, db_column='Manufacturer', null=True)),
                ('expiration_date', models.DateField(blank=True, db_column='Expiration_date', null=True)),
                ('product_type', models.CharField(blank=True, db_column='Product_type', null=True)),
                ('dosage_amount', models.CharField(blank=True, db_column='Dosage_amount', null=True)),
                ('formula_type', models.CharField(blank=True, db_column='Formula_type', null=True)),
                ('is_fda_regulated', models.BooleanField(blank=True, db_column='Is_fda_regulated', null=True)),
                ('price', models.DecimalField(blank=True, db_column='Price', decimal_places=5, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductIngredients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('supplement_id', models.IntegerField(db_column='Supplement_ID')),
                ('ingredient_id', models.IntegerField(db_column='Ingredient_id')),
            ],
            options={
                'db_table': 'Product_Ingredients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(db_column='Supplier_id', primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(db_column='Supplier_name')),
                ('contact_info', models.CharField(blank=True, db_column='Contact_info', null=True)),
            ],
            options={
                'db_table': 'Supplier',
                'managed': False,
            },
        ),
    ]
