# Generated by Django 5.2.14 on 2026-05-11 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountslogmessage_authgroup_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logcomment',
            name='supplement',
            field=models.ForeignKey(db_column='Supplement_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.inventory'),
        ),
    ]
