# Generated by Django 5.2.14 on 2026-05-11 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_adminfeedback'),
        ('pages', '0002_mymodel_product_profile_rating_delete_vitaminreview'),
    ]

    operations = [
    ]
